global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs: 
      - targets: ['localhost:8080']
